language: go
go:
  - "1.8"
  - "1.10.x"
  - master
before_install:
  - go get github.com/golang/dep/...
install:
  - $GOPATH/bin/dep ensure
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 97aec5d9-a8a3-4b1a-9e3f-1350e4a723c6
